#!/usr/bin/perl

#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

use strict;

my $commstring = $ARGV[3];
my $mac= $ARGV[1];
my $ifindex = $ARGV[2];
my $ccap = $ARGV[0];
my $datetime = "1106201220";
my $pnmfilename = join "", "PNMCcapRxMER", "_", $ccap, "_", $mac, "_", $datetime;

print $mac,"\n"; print $ccap,"\n"; print $datetime,"\n"; print $pnmfilename,"\n";

#if ($#ARGV =! 3) {
# print "Need three(!!) arguments, \n";
# print "$0 <CCAP-NAME> <MODEM MAC> <IFINDEX> \n";
#exit;
#}

system("/usr/bin/snmpset -v2c -c $commstring $ccap 1.3.6.1.4.1.4491.2.1.27.1.3.7.1.2.$ifindex x $mac");
system("/usr/bin/snmpset -v2c -c $commstring $ccap 1.3.6.1.4.1.4491.2.1.27.1.3.7.1.3.$ifindex i 1");
system("/usr/bin/snmpset -v2c -c $commstring $ccap 1.3.6.1.4.1.4491.2.1.27.1.3.7.1.4.$ifindex u 10");
system("/usr/bin/snmpset -v2c -c $commstring $ccap 1.3.6.1.4.1.4491.2.1.27.1.3.7.1.6.$ifindex s $pnmfilename");
system("/usr/bin/snmpset -v2c -c $commstring $ccap 1.3.6.1.4.1.4491.2.1.27.1.3.7.1.1.$ifindex i 1");

